### ISSUE TITLE
Laravel 5.1 config publish

### ISSUE THREAD

**Issue by tusharvikky** [rydurham/Sentinel#157]
```
[InvalidArgumentException]                                  
  There are no commands defined in the "sentinel" namespace.
```
Following providers revert back with same error as shown above.
``` 'Sentinel\SentinelServiceProvider', ``` or ``` Sentinel\SentinelServiceProvider::class, ```

**Comment by rydurham** [comment]
I am not able to re-create this problem.  Would you send me a link to your full /config/app.php file?

**Comment by tusharvikky** [comment]
http://laravel.io/bin/426Qa

I did even tried with ``` 'Sentinel\SentinelServiceProvider', ``` with same.

**Comment by rydurham** [comment]
Are you able to run commands for the other packages you are using?

**Comment by tusharvikky** [comment]
Yes.

**Comment by rydurham** [comment]
Does it show up when you run ```php artisan list```?

**Comment by tusharvikky** [comment]
I think this package is interfering with this package. https://github.com/shpasser/GaeSupportL5

**Comment by rydurham** [comment]
I am probably not going to be able to help resolve that then - you may try raising the problem on that repo.

**Comment by alvaritoe** [comment]
I am also having the same issue, which is not surprising as the documentation is horrible and you pick pieces at snatches from different postings here and there on the internet.

For example, the cartalyst sentinel instructions are completely different from the ones found on ryan durham github site. Ryan does add a lot of more things, such as having to register that at the kernel middleware. so if you did not do that when installing through cartalyst instructions and published it then you will come across this problem. Also, Ryan informs that the login and register blade are provided with Sentinel something which was not informed about on cartalyst, so I spend one afternoon yesterday building those pages for nothing. In one word. The documentation is chaotic and incomplete. Also the instructions at Cartalyist take for granted everybody was born an expert so that if that is not your case, you are doomed. There is basically no info at all at stackoverflow about Sentinel, which is not surprising because people are giving this up by the thousands.

**Comment by rydurham** [comment]
This package is completely unrelated to cartalyst/sentinel.
