### ISSUE TITLE
Cartalyst Sentinel

### ISSUE THREAD

**Issue by iboinas** [rydurham/Sentinel#163]
Hello all,

Ryan, congrats for this job!

Are u considering using Cartalyst/Sentinel2.0, that is now open source?

I will be making some kind of boilerplate backoffice with many features to manage users/groups/permissions etc, and am willing to contribute/collaborate!

**Comment by rydurham** [comment]
I am considering creating a v3.0 version of this package that uses Cartalyst\Sentinel, but I am not sure when I will have time to make that happen.

**Comment by ideadx** [comment]
:+1:

**Comment by judgej** [comment]
Ah, so this isn't anything to do with Cartalyst/Sentinel? I installed Cartalyst/Sentinel 2.0 then I installed this package, hoping it was an example front end, but have not been able to get it working. There were a few table name clashes, which got me wondering.

So to be clear, this project does not use Cartalyst/Sentinel, so that should not be installed?

**Comment by iboinas** [comment]
@judgej 
Nope, this package rydurham/Sentinel is requiring "cartalyst/sentry": "2.1.*" as you can read on its composer.json dependicies.
Cheers

**Comment by rydurham** [comment]
That is correct.  Currently, this package uses Sentry 2 and has no association with cartalyst/sentinel.

**Comment by judgej** [comment]
Okay, thanks. I just got confused with the terms - mentions of Cartalyst, Sentinel, Sentry, and version 2 etc, which made it all look rather promising.

**Comment by rydurham** [comment]
I have created a new package that attempts to do for ```cartalyst/sentinel``` what this package does for ```cartalyst/sentry```.   [You can find that package here](https://github.com/srlabs/centaur).
