### ISSUE TITLE
Naming conflict

### ISSUE THREAD

**Issue by hackel** [rydurham/Sentinel#193]
I know your package came out 6 months before Cartalyst's Sentinel, but this makes things really confusing.  You certainly deserve to have the name, so if you're attached to it, we should insist that Cartalyst change their name.  If you don't care that much, though, I would suggest renaming it to avoid this confusion.  At the very least, you could put up an explanation at the top of your README so people know what's going on!

**Comment by rydurham** [comment]
The naming conflict has been unfortunate, I agree. I had thought about trying to get them to change the name of their Sentinel package, but because this package is essentially just a wrapper for Sentry, which they also created, it seemed a bit uncouth to me to make a big deal about it. 

I am working on a new version of this library that will be released under a new name.  It won't be backwards compatible, unfortunately, but it will do essentially the same thing that this package does.  When that new library is ready I will update the readme for this package with an explanation of the naming conflict and directing them to the new repository.

**Comment by rydurham** [comment]
I have added a note to the readme which should hopefully make things a bit clearer.   Also, I have created a new bridge package for ```cartalyst/sentinel```,  [which can be found here](https://github.com/srlabs/centaur).
