### ISSUE TITLE
How can we get User data?

### ISSUE THREAD

**Issue by AlexMcowkin** [rydurham/Sentinel#234]
How can we get User data like id, email and etc?

I need use it in my views!

sorry for the questions
but I dont understand how

**Comment by rydurham** [comment]
Good question.   The best way to do this is to use the tools that Laravel itself provides.   Once you have published the config files for this package you can edit the sentry config file to tell the Sentry package to use your user model `App\User` instead of the default Sentry user.  (Make sure that your user model is extending the Sentry user class.)    From there you can do almost anything: 

```php
$user = \App\User::find(1);
echo $user->first_name;
echo $user->second_name;
```

If you fetch the user object in your controller and pass it to your custom views you should be good to go.  You can see examples of how that works in the controllers in this package.

**Comment by AlexMcowkin** [comment]
thank you

**Comment by AlexMcowkin** [comment]
how to get current logged in user id?

**Comment by rydurham** [comment]
This package is a wrapper for the [Cartalyst\Sentry](https://cartalyst.com/manual/sentry/2.1) package;  all of the methods there are available to you in your application. 

To determine if a user is currently logged in:  ```Sentry::check()```
If that method returns true, you can get the user object via ```Sentry::getUser()```

Running `getUser()`  if there is no active session available will throw an exception.

**Comment by AlexMcowkin** [comment]
yes. I did it already.
but thank you.
when I will have more free time I will write instruction for russians =)
